[package]
name = "zkboo-ripemd160"
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0-or-later"
description = "RIPEMD-160 as a ZKBoo circuit."
repository = "https://github.com/hashberg-io/zkboo-ripemd160"

[dependencies]
zkboo = { version = "0.1.0", features = ["u32"] }

[dev-dependencies]
zkboo = { version = "0.1.0", features = ["u32"] }
ripemd = "0.1"
